# Background and foreground colors
background = #E9ECEC
foreground = #1E1F24

# Standard colors
palette = 0=#E9ECEC
palette = 1=#9E1B1F
palette = 2=#2F6248
palette = 3=#7A5F14
palette = 4=#C81017
palette = 5=#8E3A46
palette = 6=#3F6E7A
palette = 7=#1E1F24

# Bright colors
palette = 8=#6E6F74
palette = 9=#E5262C
palette = 10=#427E60
palette = 11=#9A7A2A
palette = 12=#DE3A3F
palette = 13=#B04A57
palette = 14=#52889A
palette = 15=#0C0D10
