$color = rgba(248, 246, 239, 1)
$inner_color = rgba(248, 246, 239, 0.66)
$outer_color = rgba(113, 42, 0, 1)
$font_color = rgba(10, 10, 10, 1)
$placeholder_color = rgba(10, 10, 10, 0.7)
$check_color = rgba(34, 32, 0, 1)
