background            #FFFFFF
foreground            #1E1F24

# black
color0  #FFFFFF
color8  #6E6F74

# red
color1  #9E1B1F
color9  #E5262C

# green
color2  #2F6248
color10 #427E60

# yellow
color3  #7A5F14
color11 #9A7A2A

# blue
color4  #C81017
color12 #DE3A3F

# magenta
color5  #8E3A46
color13 #B04A57

#cyan
color6  #3F6E7A
color14 #52889A

#white
color7  #1E1F24
color15 #0C0D10


